;;;; Inject Protocol into cocoa objc-classes.cdb.
;;;;
;;;;   ./darm64cl --no-init --batch \
;;;;     < tools/darwin-arm64-cdb/inject-objc-protocol-class.lisp
(in-package :ccl)

(setq *warn-if-redefine-kernel* nil)
(load "library/parse-ffi.lisp")
(use-interface-dir :cocoa)

(let* ((*parse-ffi-target-ftd* *target-ftd*)
       (*ffi-global-typedefs* (make-hash-table :test 'string= :hash-function 'sxhash))
       (*ffi-global-structs* (make-hash-table :test 'string= :hash-function 'sxhash))
       (*ffi-global-unions* (make-hash-table :test 'string= :hash-function 'sxhash))
       (*ffi-global-transparent-unions* (make-hash-table :test 'string= :hash-function 'sxhash))
       (*ffi-global-objc-classes* (make-hash-table :test 'string= :hash-function 'sxhash))
       (*ffi-global-constants* (make-hash-table :test 'string= :hash-function 'sxhash))
       (*ffi-global-vars* (make-hash-table :test 'string= :hash-function 'sxhash))
       (*ffi-global-functions* (make-hash-table :test 'string= :hash-function 'sxhash))
       (*ffi-global-objc-messages* (make-hash-table :test 'string= :hash-function 'sxhash)))
  (parse-ffi "tools/darwin-arm64-cdb/objc-protocol-class.ffi")
  (format t "~&;; objc-classes=~s~%"
          (let (a) (maphash (lambda (k v) (declare (ignore v)) (push k a))
                            *ffi-global-objc-classes*) a))
  (let* ((d (require-interface-dir :cocoa))
         (dir (merge-pathnames (interface-dir-subdir d)
                               (ftd-interface-db-directory *target-ftd*)))
         (old (db-objc-classes d))
         (new (merge-pathnames "new-objc-classes.cdb" dir)))
    (with-new-db-file (cdbm new)
      (dolist (k (cdb-enumerate-keys old))
        (unless (gethash k *ffi-global-objc-classes*)
          (rletZ ((value :cdb-datum) (key :cdb-datum))
            (with-cstrs ((keyname k))
              (setf (pref key :cdb-datum.data) keyname
                    (pref key :cdb-datum.size) (length k)
                    (pref value :cdb-datum.data) (%null-ptr)
                    (pref value :cdb-datum.size) 0)
              (cdb-get old key value)
              (unless (%null-ptr-p (pref value :cdb-datum.data))
                (cdbm-put cdbm key value)
                (cdb-free (pref value :cdb-datum.data)))))))
      (maphash (lambda (name def)
                 (unless (ffi-objc-class-name def)
                   (setf (ffi-objc-class-name def) name))
                 (save-ffi-objc-class cdbm def))
               *ffi-global-objc-classes*))
    (cdb-close old)
    (setf (interface-dir-objc-classes-interface-db-file d) nil)
    (let ((path (merge-pathnames "objc-classes.cdb" dir)))
      (when (probe-file path)
        (rename-file path
                     (concatenate 'string (namestring (truename path))
                                  ".bak")))
      (rename-file new path))
    (format t "~&;; installed ~a~%" (merge-pathnames "objc-classes.cdb" dir))))
(quit 0)
