;;;; Patch cocoa functions.cdb: restore objc_msgSend* variadic prototypes.
;;;;
;;;;   ./darm64cl --no-init --batch \
;;;;     < tools/darwin-arm64-cdb/inject-objc-msgsend-prototypes.lisp
(in-package :ccl)

(defparameter *objc-msgsend-prototype-ffi*
  "tools/darwin-arm64-cdb/objc-msgsend-prototypes.ffi")

(defun %read-ffi-functions-from (path)
  (let* ((*ffi-typedefs* (make-hash-table :test 'string= :hash-function 'sxhash))
         (*ffi-unions* (make-hash-table :test 'string= :hash-function 'sxhash))
         (*ffi-transparent-unions* (make-hash-table :test 'string= :hash-function 'sxhash))
         (*ffi-structs* (make-hash-table :test 'string= :hash-function 'sxhash))
         (*ffi-objc-classes* (make-hash-table :test 'string= :hash-function 'sxhash))
         (*ffi-ordinal* -1)
         (funs ()))
    (declare (special *ffi-typedefs* *ffi-unions* *ffi-transparent-unions*
                      *ffi-structs* *ffi-objc-classes* *ffi-ordinal*))
    (with-open-file (in path)
      (let* ((*package* (find-package "KEYWORD")))
        (do* ((form (read-ffi-toplevel-form in :eof)
                    (read-ffi-toplevel-form in :eof)))
             ((eq form :eof) (nreverse funs))
          (when (eq (car form) :function)
            (push (process-ffi-function form) funs)))))))

(defun %copy-cdb-entry (old-cdb new-cdbm key-string)
  (rletZ ((value :cdb-datum)
          (key :cdb-datum))
    (with-cstrs ((keyname key-string))
      (setf (pref key :cdb-datum.data) keyname
            (pref key :cdb-datum.size) (length key-string)
            (pref value :cdb-datum.data) (%null-ptr)
            (pref value :cdb-datum.size) 0)
      (cdb-get old-cdb key value)
      (unless (%null-ptr-p (pref value :cdb-datum.data))
        (cdbm-put new-cdbm key value)
        (cdb-free (pref value :cdb-datum.data))
        t))))

(defun %inject-objc-msgsend-prototypes (&optional (dirname "cocoa"))
  (setq *warn-if-redefine-kernel* nil)
  (load "library/parse-ffi.lisp")
  (use-interface-dir (intern (string-upcase dirname) :keyword))
  (let* ((d (require-interface-dir (intern (string-upcase dirname) :keyword)))
         (old (db-functions d))
         (dir (merge-pathnames (interface-dir-subdir d)
                               (ftd-interface-db-directory *target-ftd*)))
         (newpath (merge-pathnames "new-functions.cdb" dir))
         (overrides (make-hash-table :test #'equal))
         (n 0)
         (patched 0))
    (dolist (fun (%read-ffi-functions-from *objc-msgsend-prototype-ffi*))
      (setf (gethash (ffi-function-string fun) overrides) fun))
    (format t "~&;; overriding ~d messaging prototypes~%"
            (hash-table-count overrides))
    (with-new-db-file (cdbm newpath)
      (dolist (k (cdb-enumerate-keys old))
        (let ((override (gethash k overrides)))
          (cond (override
                 (save-ffi-function cdbm override)
                 (remhash k overrides)
                 (incf patched))
                ((%copy-cdb-entry old cdbm k)
                 (incf n)))))
      (maphash (lambda (k fun)
                 (declare (ignore k))
                 (save-ffi-function cdbm fun)
                 (incf patched))
               overrides))
    (cdb-close old)
    (setf (interface-dir-functions-interface-db-file d) nil)
    (let ((path (merge-pathnames "functions.cdb" dir)))
      (when (probe-file path)
        (rename-file path
                     (concatenate 'string (namestring (truename path))
                                  "-pre-msgsend")
                     :if-exists :supersede))
      (rename-file newpath path))
    (format t "~&;; INJECT-OBJC-MSGSEND-OK copied=~d patched=~d~%" n patched)
    t))

(%inject-objc-msgsend-prototypes)
(quit 0)
