;-*- Mode:     Lisp -*-
;;;; Author:   Paul Dietz
;;;; Created:  Tue Jan 13 19:38:10 2004
;;;; Contains: Load files containing tests for section 21 (streams)

(in-package :cl-test)

(load "input-stream-p.lsp")
(load "output-stream-p.lsp")
(load "interactive-stream-p.lsp")
(load "open-stream-p.lsp")
(load "stream-element-type.lsp")
(load "streamp.lsp")
(load "read-byte.lsp")
(load "peek-char.lsp")
(load "read-char.lsp")
(load "read-char-no-hang.lsp")
(load "terpri.lsp")
(load "fresh-line.lsp")
(load "unread-char.lsp")
(load "write-char.lsp")
(load "read-line.lsp")
(load "write-string.lsp")
(load "write-line.lsp")
(load "read-sequence.lsp")
(load "write-sequence.lsp")
(load "file-length.lsp")
(load "file-position.lsp")
(load "file-string-length.lsp")
(load "open.lsp")
(load "stream-external-format.lsp")
(load "with-open-file.lsp")
(load "with-open-stream.lsp")
(load "listen.lsp")
(load "clear-input.lsp")
(load "finish-output.lsp")
(load "force-output.lsp")
(load "clear-output.lsp")
(load "make-synonym-stream.lsp")
(load "synonym-stream-symbol.lsp")
(load "make-broadcast-stream.lsp")
(load "broadcast-stream-streams.lsp")
(load "make-two-way-stream.lsp")
(load "two-way-stream-input-stream.lsp")
(load "two-way-stream-output-stream.lsp")
(load "echo-stream-input-stream.lsp")
(load "echo-stream-output-stream.lsp")
(load "make-echo-stream.lsp")
(load "concatenated-stream-streams.lsp")
(load "make-concatenated-stream.lsp")
(load "get-output-stream-string.lsp")
(load "make-string-input-stream.lsp")
(load "make-string-output-stream.lsp")
(load "with-input-from-string.lsp")
(load "with-output-to-string.lsp")
(load "stream-error-stream.lsp")

