#!/bin/sh
#
# Change the definition of CCL_DEFAULT_DIRECTORY below to refer to
# your OpenMCL installation directory.  
# Any definition of CCL_DEFAULT_DIRECTORY already present in the environment 
# takes precedence over definitions made below.

if [ -z "$CCL_DEFAULT_DIRECTORY" ]; then
  CCL_DEFAULT_DIRECTORY=/usr/local/src/ccl
fi

# This is shorter (& easier to type), making the invocation below
# a little easier to read.

DD=${CCL_DEFAULT_DIRECTORY}

# If you don't want to guess the name of the OpenMCL kernel on
# every invocation (or if you want to use a kernel with a
# non-default name), you might want to uncomment and change
# the following line:
#OPENMCL_KERNEL=some_name

# Set the CCL_DEFAULT_DIRECTORY  environment variable; 
# the lisp will use this to setup translations for the CCL: logical host.

if [ -z "$OPENMCL_KERNEL" ]; then
  case `uname -s` in
    Darwin)
    case `arch` in
      ppc*)
      OPENMCL_KERNEL=dppccl64
      ;;
      i386|x86_64)
      OPENMCL_KERNEL=dx86cl64
      ;;
    esac
    ;;
    Linux)
    case `uname -m` in
      ppc64)
      OPENMCL_KERNEL=ppccl64
      ;;
      x86_64)
      OPENMCL_KERNEL=lx86cl64
      ;;
      *)
      echo "Can't determine machine architecture.  Fix this."
      exit 1
      ;;
    esac
    ;;
    FreeBSD)
    case `uname -m` in
      amd64)
      OPENMCL_KERNEL=fx86cl64
      ;;
      *)
      echo "unsupported architecture"
      exit 1
      ;;
    esac
    ;;
    SunOS)
    case `uname -m` in
      i86pc)
      OPENMCL_KERNEL=sx86cl64
      ;;
      *)
      echo "unsupported architecture"
      exit 1
      ;;
    esac
    ;;
    *)
    echo "Can't determine host OS.  Fix this."
    exit 1
    ;;
  esac
fi

CCL_DEFAULT_DIRECTORY=${DD} exec ${DD}/${OPENMCL_KERNEL} "$@"

