;;;; Child half of tools/run-darwin-purify-smoke.sh (purified image).
(in-package :ccl)
(unless (eql (+ 1 2) 3)
  (error "purify child: (+ 1 2) => ~s" (+ 1 2)))
(let* ((f (compile nil '(lambda (x) (* x x))))
       (n (funcall f 7)))
  (unless (eql n 49)
    (error "purify child: compiled lambda => ~s" n)))
(use-interface-dir :libc)
(defun %purify-getpid () (#_getpid))
(let ((p (%purify-getpid)))
  (unless (and (integerp p) (> p 0))
    (error "purify child: getpid => ~s" p)))
(format t "~&DARWIN-PURIFY-SMOKE-OK~%")
(quit 0)
