;;;; Reload tip patches, then OBJC-SUPPORT + NSString / NSRange smoke.
;;;; Poll this — CCL smokes hang or die quickly; do not block indefinitely.
;;;;
;;;; Short NSStrings are often Apple arm64 tagged pointers (MSB set).
(in-package :ccl)
(setq *warn-if-redefine-kernel* nil)

(let* ((src (merge-pathnames "level-0/ARM64/arm64-def.lisp" (ccl-directory)))
       (form nil)
       (ff nil))
  (with-open-file (s src)
    (loop for f = (read s nil s)
          until (eq f s)
          do (cond ((and (consp f) (eq (car f) 'defarm64lapfunction)
                         (eq (cadr f) '%set-kernel-global-ptr-from-offset))
                    (setq form f))
                   ((and (consp f) (eq (car f) 'defun) (eq (cadr f) '%ff-call))
                    (setq ff f)))))
  (when form (eval form) (format t "~&lap-setter ok~%"))
  (when ff (eval ff) (format t "~&%ff-call ok~%")))

(let* ((src (merge-pathnames "compiler/ARM64/arm64-backend.lisp" (ccl-directory)))
       (forms ()))
  (with-open-file (s src)
    (loop for f = (read s nil s)
          until (eq f s)
          when (and (consp f) (eq (car f) 'defun)
                    (eq (cadr f) 'arm64::expand-ff-call))
          do (push f forms)))
  (dolist (f (nreverse forms)) (eval f))
  (setf (ftd-ff-call-expand-function *target-ftd*) #'arm64-darwin::expand-ff-call)
  (format t "~&expand-ff-call ok (~d)~%" (length forms)))

(let* ((src (merge-pathnames "lib/foreign-types.lisp" (ccl-directory)))
       (wanted '(objc-messaging-entry-name-p %external-call-expander))
       (forms ()))
  (with-open-file (s src)
    (loop for f = (read s nil s)
          until (eq f s)
          when (and (consp f) (eq (car f) 'defun) (member (cadr f) wanted))
          do (push f forms)))
  (dolist (f (nreverse forms)) (eval f))
  (format t "~&expander ok (~d)~%" (length forms)))

(let* ((src (merge-pathnames "compiler/ARM64/arm642.lisp" (ccl-directory)))
       (helpers ())
       (ffcall nil))
  (with-open-file (s src)
    (loop for f = (read s nil s)
          until (eq f s)
          do (cond ((and (consp f)
                         (member (car f) '(defun defarm642))
                         (member (cadr f)
                                 '(arm642-aapcs64-stack-arg-bytes
                                   arm642-align-up
                                   arm642-aapcs64-ff-call)))
                    (if (eq (cadr f) 'arm642-aapcs64-ff-call)
                      (setq ffcall f)
                      (push f helpers))))))
  (dolist (h (nreverse helpers)) (eval h))
  (eval ffcall)
  (format t "~&aapcs64 ok~%"))

(format t "~&requiring OBJC-SUPPORT...~%")
(finish-output)
(require "OBJC-SUPPORT")
(format t "~&objc-support loaded~%")
(finish-output)

;; Override image/fasl copy: arm64 tagged pointers use bit63, not x86 low nibble.
(defun tagged-objc-instance-p (p)
  (when *objc-runtime-uses-tags*
    (let* ((raw (%ptr-to-int p)))
      (when (logbitp 63 raw)
        (let* ((basic (logand raw #x7)))
          (declare (fixnum basic))
          (if (eql basic 7)
            (logior #x100 (ldb (byte 8 55) raw))
            basic))))))
(format t "~&tagged-ptr override ok~%")

(let* ((s (%make-nsstring "darwinarm64"))
       (len (#/length s)))
  (format t "~&s=~s len=~s~%" s len)
  (finish-output)
  (unless (and (integerp len) (eql len 11))
    (error "NSString length => ~s" len)))

(let* ((s (%make-nsstring "abcdef"))
       (r (ns:make-ns-range 1 3))
       (sub (#/substringWithRange: s r))
       (cstr (%get-cstring (#/UTF8String sub))))
  (format t "~&substring=~s (recv tagged=~s)~%"
          cstr (not (null (tagged-objc-instance-p s))))
  (finish-output)
  (unless (equal cstr "bcd")
    (error "substringWithRange: => ~s" cstr)))

(let* ((fmt (%make-nsstring "%d-%@"))
       (arg (%make-nsstring "ok"))
       (formatted (#/stringWithFormat: ns:ns-string fmt 1 arg))
       (cstr (%get-cstring (#/UTF8String formatted))))
  (format t "~&format=~s~%" cstr)
  (finish-output)
  (unless (equal cstr "1-ok")
    (error "stringWithFormat: => ~s" cstr)))

(unless (find-class 'ns:protocol nil)
  (error "ns:protocol class missing"))
(format t "~&protocol-class=~s~%" (find-class 'ns:protocol nil))
(finish-output)

(format t "~&DARWIN-OBJC-BRIDGE-SMOKE-OK~%")
(finish-output)
(quit 0)
